use db_sneakers
go

-- Brand (id, name, email)
insert into Brand(name, email) values('Adidas', 'adidas@gmail.com')
insert into Brand(name, email) values('Nike', 'nike@gmail.com')

-- Product (id, name, idBrand, image, describe, quantity, cost, saleDate)
SET IDENTITY_INSERT [dbo].[Product] ON 
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (1, 1, N'Women''s adidas Originals NMD_Racer Primeknit Shoes', N'img/product/adidas/1.jpg', N'Channeling the streamlined look of an ''80s racer, these shoes are updated with modern features. The foot-hugging adidas Primeknit upper offers a soft, breathable feel. The Boost midsole provides responsive comfort accented with a contrast-color EVA heel plug. Embroidered details add a distinctive finish.', 5, 2261548.5, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (2, 1, N'Women''s adidas Originals Sleek Shoes', N'img/product/adidas/2.jpg', N'A modern take on adidas sport heritage, tailored just for women. Perforated 3-Stripes on the leather upper of these shoes offer a sleek look that mirrors iconic tennis styles.', 5, 1145702.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (3, 1, N'Women''s adidas Swim Puka Slippers ', N'img/product/adidas/3.jpg', N'These adidas Puka slippers for women''s come with slim straps for a great fit. Feature performance logo on the footbed and textured Rubber outsole that gives unique comfort.', 5, 180646.422, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (4, 1, N'Women''s adidas Sport Inspired Questar Ride Shoes', N'img/product/adidas/4.jpg', N'Inspired by modern tech runners, these women''s shoes step out with unexpected style. They''re built with a breathable knit upper, while the heel offers the extra support of an Achilles-hugging design. The cushioned midsole provides a soft landing with every stride.', 5, 1055228.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (5, 1, N'Women''s adidas Originals Taekwondo Shoes', N'img/product/adidas/5.jpg', N'This design is inspired by vintage Taekwondo styles originally worn to perfect high kicks and rapid foot strikes. The canvas shoes make a streetwear fashion statement as a chic, foot-hugging slip-on. They''re shaped for a narrow, women''s-specific fit and ride on a soft gum rubber outsole.', 5, 1206018.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (6, 1, N'Women''s adidas Sport Inspired Duramo Lite 2.0 Shoes', N'img/product/adidas/6.jpg', N'Refine your interval training in these women''s versatile running-inspired shoes. Featuring a lightweight mesh and synthetic upper, they combine responsive midsole cushioning with a soft collar that reduces ankle pressure. ', 5, 579033.6, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (7, 1, N'Women''s adidas Sport Inspired Duramo Lite 2.0 Shoes', N'img/product/adidas/7.jpg', N'Refine your interval training in these women''s versatile running-inspired shoes. Featuring a lightweight mesh and synthetic upper, they combine responsive midsole cushioning with a soft collar that reduces ankle pressure. ', 5, 723490.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (8, 1, N'Women''s adidas Swim Puka Slippers ', N'img/product/adidas/8.jpg', N'These adidas Puka slippers for women''s come with slim straps for a great fit. Feature performance logo on the footbed and textured Rubber outsole that gives unique comfort.', 5, 180646.422, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (9, 1, N'WOMEN''S ADIDAS RUNNING DURAMO 9 SHOES', N'img/product/adidas/9.jpg', N'These women''s neutral running shoes will get you on the road to your goals. A sandwich mesh upper offers lightweight breathability, while a seamless print overlay adds support for a stable stride. The midsole offers pillow-soft Cloudfoam cushioning that eases every stride.', 5, 844122.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (10, 1, N'Men''s adidas Originals Forest Grove Shoes', N'img/product/adidas/10.jpg', N'The Forest Grove brings back the look of the adidas Oregon running design from the ''80s. A favourite for marathon training, it had a distinctive look and feel with shock-absorbing cushioning and a web-wrapped midsole. These streetwear shoes echo the original look with a textured nubuck and mesh upper. A web overlay on the midsole adds authentic Oregon style.', 5, 1193955.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (11, 1, N'Women''s adidas Originals Swift Run Shoes', N'img/product/adidas/11.jpg', N'The Swift distills decades of adidas heritage running designs. Made for casual everyday wear, these lightweight knit shoes come with a sleek shape and a supportive yet flexible feel. They stand out with embroidered accents and smooth welded details. An EVA midsole adds all-day wearability.', 5, 1374903.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (12, 1, N'Women''s adidas Originals Continental Vulc Shoes', N'img/product/adidas/12.jpg', N'These low-profile shoes come in a pastel color for a feminine touch. A mix of nubuck and canvas on the upper adds texture. The suede toe cap is abrasion-resistant so they look fresh and new longer. A vulcanized outsole makes them durable.', 5, 1193955.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (13, 1, N'Women''s adidas Running Duramo 9 Shoes', N'img/product/adidas/13.jpg', N'These women''s neutral running shoes will get you on the road to your goals. A sandwich mesh upper offers lightweight breathability, while a seamless print overlay adds support for a stable stride. The midsole offers pillow-soft Cloudfoam cushioning that eases every stride.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (14, 1, N'Women''s adidas Originals Supercourt Shoes', N'img/product/adidas/14.jpg', N'Forty years of court style, refined to the essentials. The clean, simple lines and supple leather upper of these shoes are a nod to tennis history. Iconic perforated 3-Stripes and a contrasting Trefoil heel tab give them a timeless look.', 5, 1374903.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (15, 1, N'Men''s adidas Sport Inspired Response Trail Shoes', N'img/product/adidas/15.jpg', N'When the road turns to trail, all that matters is what lies ahead. These running shoes deliver a plush ride and confident grip in a fresh, sporty look. Cloudfoam cushioning feels ultra-soft while the aggressive outsole grabs on in all directions. The multilayer upper and sleek 3-Stripes elevate your look when you get back to town.', 5, 1206018.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (16, 1, N'Women''s adidas Running Cosmic 2 Shoes', N'img/product/adidas/16.jpg', N'These women''s running shoes have a breathable mesh upper to keep your feet ventilated on your daily runs. The Cloudfoam midsole provides plush cushioning with every stride, and a high-wear outsole holds up over time.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (17, 1, N'Women''s adidas Sport Inspired Storm Runner Shoes', N'img/product/adidas/17.jpg', N'A fast, lightweight adidas stormrunner shoes for women. These running-inspired shoes are very comfortable for your daily routine. Made with textile upper and Cloudfoam midsole along with rubber outsole these shoes will provide comfort to your feet all day long. ', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (18, 1, N'Women''s adidas Sport Inspired Quickspike Shoes', N'img/product/adidas/18.jpg', N'These women''s running-inspired shoes feature a breathable mesh upper with a comfort collar, while a moulded overlay provides lightweight support. The soft Cloudfoam cushioning in the one-piece midsole and outsole provides comfort that lasts all day long.', 5, 602858.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (19, 1, N'WOMEN''S ADIDAS SWIM CLOUDFOAM FLIP FLOPS', N'img/product/adidas/19.jpg', N'A minimalist design with maximum post-workout comfort. These women''s thong sandals feature a soft strap connected to a Cloudfoam footbed that cushions every step and dries quickly. A durable rubber outsole adds long-lasting wear.', 5, 497305.4, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (20, 1, N'Women''s adidas Sport Inspired Lite Racer Shoes', N'img/product/adidas/20.jpg', N'Unstoppable style. These shoes borrow their lightweight look and feel from celebrated runners. The airy mesh upper has a clean finish with monochrome 3-Stripes. Plush cushioning helps keep the ride smooth.', 5, 648095.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (21, 1, N'Women''s adidas Running Duramo 9 Shoes', N'img/product/adidas/21.jpg', N'These women''s neutral running shoes will get you on the road to your goals. A sandwich mesh upper offers lightweight breathability, while a seamless print overlay adds support for a stable stride. The midsole offers pillow-soft Cloudfoam cushioning that eases every stride.', 5, 844122.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (22, 1, N'Women''s adidas Sport Inspired Arcadeis Shoes', N'img/product/adidas/22.jpg', N'These women''s running-inspired shoes cradle your feet with a net mesh upper. Pillow-soft Cloudfoam cushioning in the one-piece midsole and outsole provides comfort that lasts all day long.', 5, 648095.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (23, 1, N'Women''s adidas Sport Inspired Videll Shoes', N'img/product/adidas/23.jpg', N'Extremely functional and subtle running-inspired shoes for women. Feature a textile-mesh upper and synthetic overlays. EVA cushioning adds extra comfort. The running 3-Stripes on the sides along with an interesting all-over print on the upper add to it''s appeal.', 5, 687300.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (24, 1, N'Women''s adidas Running EnergyFalcon X Shoes', N'img/product/adidas/24.jpg', N'When you dig deep to reach your goals, these running shoes offer the support and stability you need. Every step feels pillow-soft with plush cushioning and an OrthoLiteÃ‚Â® sockliner for comfort. A flowing TPU heel counter and thin support cage keep the foot centred and stable. The durable outsole is made for logging many miles.', 5, 994912.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (25, 1, N'Women''s adidas Sport Inspired Videll Shoes', N'img/product/adidas/25.jpg', N'Extremely functional and subtle running-inspired shoes for women. Feature a textile mesh upper and synthetic overlays. EVA cushioning adds extra comfort. The running 3-Stripes on the sides along with an interesting all-over print on the upper add to it''s appeal.', 5, 572700.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (26, 1, N'Women''s adidas Running Hellion Z Shoes', N'img/product/adidas/26.jpg', N'Great everyday trainer for the runner in you to go that extra mile. The adidas Hellion Z shoes comes with mesh upper for providing lightweight and breathability to your feet.', 5, 596826.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (27, 1, N'Women''s adidas Sport Inspired Videll Shoes', N'img/product/adidas/27.jpg', N'Extremely functional and subtle running-inspired shoes for women. Feature a textile-mesh upper and synthetic overlays. EVA cushioning adds extra comfort. The running 3-Stripes on the sides along with an interesting all-over print on the upper add to it''s appeal.', 5, 687300.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (28, 1, N'Women''s adidas Sport Inspired Arcadeis Shoes', N'img/product/adidas/28.jpg', N'These women''s running-inspired shoes cradle your feet with a net mesh upper. Pillow-soft Cloudfoam cushioning in the one-piece midsole and outsole provides comfort that lasts all day long.', 5, 648095.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (29, 1, N'Women''s adidas Sport Inspired Cloudfoam Pure Shoes', N'img/product/adidas/29.jpg', N'These women''s running-inspired shoes cradle your feet with a mesh upper and a Memory Foam footbed that conforms to the shape of your foot. Pillow-soft Cloudfoam cushioning in the one-piece midsole and outsole provides comfort that lasts all day long.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (30, 1, N'Women''s adidas Running Hellion Z Shoes', N'img/product/adidas/30.jpg', N'The adidas Hellion Z Running shoes for women with new design pattern for any runner looking for trendy yet extremely comfortable running shoe. An excellent combination of breathable Mesh with synthetic overlays on the upper makes it very comfortable for your feet on the run. Durable, non slippery, blown out one piece super grip EVA midsole and Rubber outsole ensures maximum stability and grip on the ground.', 5, 596826.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (31, 1, N'Women''s adidas Sport Inspired Yking 2.0 Shoes', N'img/product/adidas/31.jpg', N'These lightweight running-inspired shoes for women give all round comfort, cushioning, durability & support in a simplistic design. The mesh upper ensure breathability and durability. Lightstrike EVA midsole gives you cushioning you need everyday and Rubber outsole provides durability.', 5, 596826.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (32, 1, N'Women''s adidas Running Hellion Z Shoes', N'img/product/adidas/32.jpg', N'The adidas Hellion Z Running shoes for women with new design pattern for any runner looking for trendy yet extremely comfortable running shoe. An excellent combination of breathable Mesh with synthetic overlays on the upper makes it very comfortable for your feet on the run. Durable, non slippery, blown out one piece super grip EVA midsole and Rubber outsole ensures maximum stability and grip on the ground.', 5, 596826.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (33, 1, N'Women''s adidas Sport Inspired Yking 2.0 Shoes', N'img/product/adidas/33.jpg', N'These lightweight running-inspired shoes for women give all round comfort, cushioning, durability & support in a simplistic design. The mesh upper ensure breathability and durability. Lightstrike EVA midsole gives you cushioning you need everyday and Rubber outsole provides durability.', 5, 596826.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (34, 1, N'Women''s adidas Sport Inspired RunFalcon Shoes', N'img/product/adidas/34.jpg', N'Start clocking miles in these lightweight running shoes. On the treadmill or the streets, they add comfort to each step with soft cushioning. The supportive trainers have an airy material-mix upper and a midfoot cage for extra support.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (35, 1, N'Women''s adidas Sport Inspired Quickspike Shoes', N'img/product/adidas/35.jpg', N'These women''s running-inspired shoes feature a breathable mesh upper with a comfort collar, while a moulded overlay provides lightweight support. The soft Cloudfoam cushioning in the one-piece midsole and outsole provides comfort that lasts all day long.', 5, 723490.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (36, 1, N'Women''s adidas Sport Inspired Blaze Runner Shoes', N'img/product/adidas/36.jpg', N'Extremely functional and subtle running-inspired shoes for women. The breathable and lightweight Knit-Mesh offer extended ventilation and comfort. Cloudfoam midsole and full Adiwear outsole provides durability.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (37, 1, N'Women''s adidas Sport Inspired Lite Racer CLN Shoes', N'img/product/adidas/37.jpg', N'Designed with sleek lines for a minimalist look, these shoes have a light and breathable mesh upper. Pillowy cushioning delivers comfort that lasts all day.', 5, 832059.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (38, 1, N'Women''s adidas Sport Inspired Blaze Runner Shoes', N'img/product/adidas/38.jpg', N'Extremely functional and subtle running-inspired shoes for women. The breathable and lightweight Knit-Mesh offer extended ventilation and comfort. Cloudfoam midsole and full Adiwear outsole provides durability.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (39, 1, N'Women''s adidas Nova Run X Shoes', N'img/product/adidas/39.jpg', N'Being comfortable on your run is just as important as winning the race. These shoes combine soft, supportive Cloudfoam cushioning with a durable Adiwear outsole for comprehensive control and an energised ride. The mesh upper features a foot-hugging, no-sew fit for a locked-in feel.', 5, 1555851.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (40, 1, N'Women''s adidas Sport Inspired Questar Flow Shoes', N'img/product/adidas/40.jpg', N'Ready for the streets. These shoes borrow their modern look and feel from lightweight runners. They have a flexible knit upper with floating 3-Stripes integrated into the lacing system. Pillow-soft midsole and outsole cushioning provides all-day comfort.', 5, 1193955.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (41, 1, N'Women''s adidas Sport Inspired Questar Flow Shoes', N'img/product/adidas/41.jpg', N'Ready for the streets. These shoes borrow their modern look and feel from lightweight runners. They have a flexible knit upper with floating 3-Stripes integrated into the lacing system. Pillow-soft midsole and outsole cushioning provides all-day comfort.', 5, 1193955.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (42, 1, N'Women''s adidas Running EnergyFalcon X Shoes', N'img/product/adidas/42.jpg', N'When you dig deep to reach your goals, these running shoes offer the support and stability you need. Every step feels pillow-soft with plush cushioning and an OrthoLiteÃ‚Â® sockliner for comfort. A flowing TPU heel counter and thin support cage keep the foot centred and stable. The durable outsole is made for logging many miles.', 5, 1193955.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (43, 1, N'Women''s adidas Running Asweego Shoes', N'img/product/adidas/43.jpg', N'Shoes with flexibility and responsiveness for multisport training. These shoes have a knit textile upper that hugs the foot for a sock-like fit. Pillow-like midsole cushioning provides long-lasting comfort. Durable rubber inserts at the forefoot and heel provide added grip so you''re ready for unexpected terrain.', 5, 1374903.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (44, 1, N'Women''s adidas Running Sooraj Shoes', N'img/product/adidas/44.jpg', N'Fast and sleek. Ready to go. These women''s running shoes feature a streamlined, low-profile design and pillow-soft Cloudfoam cushioning for plush landings. The mesh upper delivers a speedy look in fun colours and 3-Stripes.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (45, 1, N'Women''s adidas Sport Inspired Questar Ride Shoes', N'img/product/adidas/45.jpg', N'Inspired by modern tech runners, these women''s shoes step out with unexpected style. A two-tone mesh upper keeps the feel flexible and mixes with a sculpted Cloudfoam midsole and contrast heel counter.', 5, 1266334.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (46, 1, N'Men''s adidas Sport Inspired Run 70s Shoes', N'img/product/adidas/46.jpg', N'These running-inspired shoes are designed with a mesh upper and a textile lining for flexible, all-day comfort. 3-Stripes and a rubber outsole give the shoes a stylish sign-off.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (47, 1, N'Women''s adidas Running Asweerun Shoes', N'img/product/adidas/47.jpg', N'Aspire to greatness. These running shoes for women are made with an airy, lightweight mesh upper. The durable rubber outsole grips the pavement for added stability. A cushioned midsole brings comfort to each step.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (48, 1, N'Women''s adidas Sport Inspired Archivo Shoes', N'img/product/adidas/48.jpg', N'A mix of modern comfort and authentic adidas heritage. These running-inspired shoes treat your feet to superior cushioning and an ultra-plush ride with a Cloudfoam midsole and soft sockliner. A sleek mesh upper features suede overlays with subtle 3-Stripes for sporty style.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (49, 1, N'Women''s Sport Inspired Yking 2.0 Shoes', N'img/product/adidas/49.jpg', N'These lightweight running-inspired shoes for women give all round comfort, cushioning, durability & support in a simplistic design. The mesh upper ensure breathability and durability. Lightstrike EVA midsole gives you cushioning you need everyday and Rubber outsole provides durability.', 5, 596826.8, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (50, 1, N'Women''s adidas Sport Inspired Archivo Shoes', N'img/product/adidas/50.jpg', N'A mix of modern comfort and authentic adidas heritage. These running-inspired shoes treat your feet to superior cushioning and an ultra-plush ride with a Cloudfoam midsole and soft sockliner. A sleek mesh upper features suede overlays with subtle 3-Stripes for sporty style.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (51, 1, N'Women''s adidas Running Response Trail X Shoes', N'img/product/adidas/51.jpg', N'When the road turns to trail, all that matters is what lies ahead. These running shoes deliver a plush ride and confident grip in a fresh, sporty look. Cloudfoam cushioning feels ultra-soft while the aggressive outsole grabs on in all directions. The multilayer upper and sleek 3-Stripes elevate your look when you get back to town.', 5, 1266334.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (52, 1, N'Women''s adidas Running EnergyFalcon X Shoes', N'img/product/adidas/52.jpg', N'When you dig deep to reach your goals, these running shoes offer the support and stability you need. Every step feels pillow-soft with plush cushioning and an OrthoLiteÃ‚Â® sockliner for comfort. A flowing TPU heel counter and thin support cage keep the foot centred and stable. The durable outsole is made for logging many miles.', 5, 1193955.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (53, 1, N'Women''s adidas Originals Marathon Tech Shoes', N'img/product/adidas/53.jpg', N'These shoes draft off the Marathon TR, a trail-running pioneer that debuted in 1979. The upper mixes breathable mesh and suede overlays with metallic details. A grid print on the midsole highlights the addition of responsive Boost cushioning.', 5, 2171074.5, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (54, 1, N'Women''s adidas Originals U_Path Run Shoes', N'img/product/adidas/54.jpg', N'The U_Path offers a sleek combination of retro and modern. These shoes are built of soft, breathable mesh for everyday wear. The unique D-ring lacing system is inspired by a ''70s running sneaker design. A bungee heel piece provides support, and a lightweight EVA midsole adds all-day wearability.', 5, 1447282.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (55, 1, N'Men''s adidas Sport Inspired Drogo Shoes ', N'img/product/adidas/55.jpg', N'The adidas running-inspired shoes for men. An excellent combination of breathable Mesh with synthetic overlays on the upper makes it very comfortable for your feet on the run. Durable and non slippery one piece super grip EVA midsole and outsole ensures maximum stability and grip on the ground.', 5, 406831.4, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (56, 1, N'Women''s adidas Originals Stan Smith Shoes', N'img/product/adidas/56.jpg', N'Since it first hit the courts in the early ''70s, the Stan Smith has become legendary for its timeless style. These shoes pay tribute to the iconic design by preserving the low-profile cupsole and perforated 3-Stripes. The allover floral print on the upper gives this version a fresh twist.', 5, 1447282.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (57, 1, N'Women''s adidas Running Sooraj Shoes', N'img/product/adidas/57.jpg', N'Fast and sleek. Ready to go. These women''s running shoes feature a streamlined, low-profile design and pillow-soft Cloudfoam cushioning for plush landings. The mesh upper delivers a speedy look in fun colours and 3-Stripes.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (58, 1, N'Women''s adidas Originals U_Path Run Shoes', N'img/product/adidas/58.jpg', N'The U_Path offers a sleek combination of retro and modern. These shoes are built of soft, breathable mesh for everyday wear. The unique D-ring lacing system is inspired by a ''70s running sneaker design. A bungee heel piece provides support, and a lightweight EVA midsole adds all-day wearability.', 5, 1447282.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (59, 1, N'Men''s adidas Sport Inspired Run 70s Shoes', N'img/product/adidas/59.jpg', N'These running-inspired shoes are designed with a mesh upper and a textile lining for flexible, all-day comfort. 3-Stripes and a rubber outsole give the shoes a stylish sign-off.', 5, 1013007.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (60, 1, N'Men''s adidas Running Nayo 1.0 shoes', N'img/product/adidas/60.jpg', N'The adidas Nayo 1.0 shoes for men. These lightweight running shoes give all round comfort, cushioning, durability & support in a simplistic design. The mesh upper ensure breathability and durability while the Light strike EVA midsole provides premium cushioning''s. Full Rubber outsole provides durability.', 5, 603160, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (61, 1, N'Men''s adidas Sports Inspired Lite Racer Shoes', N'img/product/adidas/61.jpg', N'The ultra-lightweight build of these shoes takes a running-inspired style to the streets. The sporty look has a breathable and durable mesh upper with stitched-on 3-Stripes. EVA cushioning provides lightweight comfort for every step.', 5, 648095.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (62, 1, N'Men''s adidas Running Nepton 2.0 Shoes', N'img/product/adidas/62.jpg', N'Sleek design with reflective three stripes makes it a contemporary yet functional shoe. Breathable textile upper for maximum ventilation and a cushioned midsole provides all-day comfort with rubber outsole for best durability in high wear areas. ', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (63, 1, N'Women''s adidas Running Aseerun Shoes', N'img/product/adidas/63.jpg', N'Aspire to greatness. These running shoes for women are made with an airy, lightweight mesh upper. The durable rubber outsole grips the pavement for added stability. A cushioned midsole brings comfort to each step.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (64, 1, N'Men''s adidas Running Torik Shoes', N'img/product/adidas/64.jpg', N'A well cushioned shoe with a fresher look that will appeal to young runners. Features Mesh upper for maximum ventilation, lightstrike IMEVA midsole with visible adiprene providing protection from harmful impact forces and durable Rubber outsole for long-lasting wear. ', 5, 723490.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (65, 1, N'Men''s adidas Sport Inspired Kalus 1.0 Shoes', N'img/product/adidas/65.jpg', N'A well cushioned running-inspired shoes with a fresher look that will appeal to all. Features Mesh upper for maximum ventilation, lightstrike IMEVA midsole with visible adiprene providing protection from harmful impact forces and durable Rubber outsole for long-lasting wear. ', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (66, 1, N'Men''s adidas Running Duramo 9 Shoes', N'img/product/adidas/66.jpg', N'These men''s running shoes will get you on the road to your goals. A sandwich mesh upper offers lightweight breathability, while a seamless print overlay adds support for a stable stride. The midsole offers pillow-soft Cloudfoam cushioning that eases every stride.', 5, 1085386.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (67, 1, N'Women''s adidas Originals Continental 80 Shoes', N'img/product/adidas/67.jpg', N'The Continental 80 is an authentic reissue of an indoor sneaker from the ''80s. These leather low top shoes show off a swooping stripe on the side and a split rubber cupsole.', 5, 1447282.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (68, 1, N'MEN''S adidas  RUNNING YAMO 1.0 SHOES', N'img/product/adidas/68.jpg', N'The adidas Yamo 1.0 shoes for men. These lightweight running shoes have a combination of Synthetic with double layer Mesh ensure breathability and durability while the Lightstrike EVA midsole provides premium cushionings. Full Rubber outsole provides durability.', 5, 723490.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (69, 1, N'men''s ADIDAS RUNNING NEBULAR 1.0 SHOES', N'img/product/adidas/69.jpg', N'The premium looking adidas Nebular 1.0 Running shoes for men crafted with Mesh overlays which make it lightweight. The breathable sandwich Mesh offer extended ventilation and comfort. Light strike IMEVA midsole with full Rubber outsole provides durability.', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (70, 1, N'MEN''S ADIDAS RUNNING LEGUS SHOES', N'img/product/adidas/70.jpg', N'Get maximum support, comfort and a refreshed look with these adidas Legus shoes for men. The textile mesh upper is breathable and has a sock-like fit and the supportive cage in the shoe''s midfoot provides midfoot lockdown. CLOUDFOAM gives  instant step in-comfort, long-lasting responsive cushioning and a super-plush feel and the Rubber outsole gives ultimate durability.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (71, 1, N'Men''s adidas Originals Supercourt Shoes', N'img/product/adidas/71.jpg', N'The Supercourt distills 40 years of adidas tennis style. This version of the classic low-profile shoes has perforated 3-Stripes on a crisp leather upper. Decorative stitching and overlays add texture and depth for a multilayered look.', 5, 1374903.25, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (72, 1, N'Men''s adidas Toe Side II Slippers', N'img/product/adidas/72.jpg', N'The adidas casual sandals for men with a striking camouflage design. Features stylish webbing straps, Diecut EVA midsole for stable cushioning and abrasion resistant rubber outsole with wet and dry traction pattern. ', 5, 234930.813, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (73, 1, N'Men''s adidas Outdoor Elevate Sandals', N'img/product/adidas/73.jpg', N'Stylish and sleek adidas sandals for women are extremely lightweight. Adjustable straps enable optimal fit while the Synthetic upper and soft EVA footbed with fitted heel provide enhanced comfort. Rubber outsole with wet and dry traction pattern keeps you in control.', 5, 421910.4, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (74, 1, N'men''s ADIDAS RUNNING NEBULAR 1.0 SHOES', N'img/product/adidas/74.jpg', N'The premium looking adidas Nebular 1.0 Running shoes for men crafted with Mesh overlays which make it lightweight. The breathable sandwich Mesh offer extended ventilation and comfort. Light strike IMEVA midsole with full Rubber outsole provides durability.', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (75, 1, N'Men''s adidas Originals Superstar Shoes', N'img/product/adidas/75.jpg', N'These trainers born in the ''70s keep the look classic with a coated leather upper. They feature all the authentic details, including zigzag edging on the tonal 3-Stripes and the signature rubber shell toe.', 5, 2412338.5, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (76, 1, N'Men''s adidas Originals Stan Smith Shoes', N'img/product/adidas/76.jpg', N'The chic minimalism of the Stan Smith invites endless variation. These men''s shoes are updated for the season with a subtle twist. A small cutout Trefoil makes a surprise appearance on the smooth leather upper.', 5, 1206018.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (77, 1, N'Men''s adidas Sport Inspired Duramo Lite 2.0 Shoes', N'img/product/adidas/77.jpg', N'Refine your interval training in these men''s versatile running-inspired shoes. Featuring a lightweight mesh and synthetic upper, they combine responsive midsole cushioning with a soft collar that reduces ankle pressure. ', 5, 753648.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (78, 1, N'Men''s adidas Swim Ozor III Slippers', N'img/product/adidas/78.jpg', N'The simple and stylish adidas Ozor III slippers for men. Best suited to match with your swimwear, these printed slippers have a soft footbed for additional comfort for your feet while the Synthetic strap with vents provides breathability proper fitting.', 5, 234930.813, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (79, 1, N'Men''s adidas Swim Gadi Slippers', N'img/product/adidas/79.jpg', N'These thongs are primed for warm-weather fun in a simple design with an urban inspired city graphic print on footbed and adidas brading featured on heel and strap.', 5, 225883.422, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (80, 1, N'MEN''S ADIDAS RUNNING LEGUS SHOES', N'img/product/adidas/80.jpg', N'Get maximum support, comfort and a refreshed look with these adidas Legus shoes for men. The textile mesh upper is breathable and has a sock-like fit and the supportive cage in the shoe''s midfoot provides midfoot lockdown. CLOUDFOAM gives  instant step in-comfort, long-lasting responsive cushioning and a super-plush feel and the Rubber outsole gives ultimate durability.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (81, 1, N'Men''s adidas Originals CAMPUS Low Shoes ', N'img/product/adidas/81.jpg', N'This men''s classic sneaker stays close to its trendsetting ''80s design, while staying modern for today''s streets. Boasting a suede upper with contrast 3-Stripes and heel patch, these shoes feature a reinforced toe cap. The cupsole leaves a herringbone-pattern footprint for a retro twist.', 5, 1206018.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (82, 1, N'MEN''S ADIDAS RUNNING HELKIN 3.0 SHOES', N'img/product/adidas/82.jpg', N'Style and performance go hand in hand in this adidas Helkin 3.0 Running shoes for men. The breathable upper Knit-Mesh offers maximum ventilation. EVA midsole and rubber outsole. ', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (83, 1, N'MEN''S ADIDAS RUNNING LEGUS 1.0 SHOES', N'img/product/adidas/83.jpg', N'Get maximum support, comfort and a refreshed look with these adidas Legus shoes for men. The textile mesh upper is breathable and has a sock-like fit and the supportive cage in the shoe''s midfoot provides midfoot lockdown. CLOUDFOAM gives  instant step in-comfort, long-lasting responsive cushioning and a super-plush feel and the Rubber outsole gives ultimate durability.', 5, 844122.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (84, 1, N'Men''s adidas Running Kollide Shoes', N'img/product/adidas/84.jpg', N'Extremely functional and subtle running shoes for men. The breathable and lightweight textile upper offer extended ventilation and comfort. The Cloudfoam midsole gives you cushioning you need everyday and Rubber outsole provides durability.', 5, 723490.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (85, 1, N'Men''s adidas Running Edge PR Shoes', N'img/product/adidas/85.jpg', N'With a springy midsole and breathable upper, these men''s running shoes are inspired by a racing flat. Bounce provides flexible cushioning for energised comfort, and a mesh upper keeps them lightweight.', 5, 1206018.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (86, 1, N'Men''s adidas Originals FuturePacer Shoes', N'img/product/adidas/86.jpg', N'The Futurepacer reworks the revolutionary design of the 1984 Micropacer shoes to challenge old ideas of what a sneaker should look like. This futuristic style makes a statement with a fully reflective stretchy upper and a mix of premium leathers. A Boost midsole with textured EVA plugs returns energy with every stride.', 5, 3015498.5, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (87, 1, N'MEN''S ADIDAS ORIGINALS MICROPACER X R1 SHOES', N'img/product/adidas/87.jpg', N'These shoes are a hybrid of retro and modern adidas designs. Made in leather with suede overlays, they combine the midsole look of the NMD_R1 with the vintage-tech upper of the 1984 Micropacer, born during an era when wearable technology was an exciting new concept. The Boost midsole adds durable energy return.', 5, 2412338.5, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (88, 1, N'Men''s adidas Outdoor Andorian Shoes', N'img/product/adidas/88.jpg', N'The adidas Andorian shoes for men are crafted with a strong, grippy outsole inspired by mountain bike tires, and a super durable Mesh and Synthetic upper. They come with Lightweight EVA midsole for stability and cushioning while the abrasion resistant rubber outsole provides aggressive traction for rough terrain.', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (89, 1, N'Men''s adidas Sport Inspired Advantage Base Shoes', N'img/product/adidas/89.jpg', N'A court look emerges on the streets. These shoes have a sleek textile upper and a textured rubber cupsole.', 5, 753648.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (90, 1, N'Men''s adidas Running Galaxy 4 Shoes', N'img/product/adidas/90.jpg', N'Add miles to your running regimen in these men''s shoes. They have a durable and breathable mesh upper with a midfoot cage for added support and stability. The plush Cloudfoam midsole delivers ultra-soft cushioning.', 5, 798885.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (91, 1, N'MEN''S ADIDAS ESSENTIALS EEZAY FLIP-FLOPS', N'img/product/adidas/91.jpg', N'These men''s classic flip-flops offer a clean beach design. Featuring midsole cushioning, this essential footwear provides lightweight comfort in a simple silhouette.', 5, 301278.4, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (92, 1, N'men''s ADIDAS ORIGINALS PW HU HOLI STAN SMITH SHOES', N'img/product/adidas/92.jpg', N'A style icon gets some love from one of today''s top trendsetters. Pharrell Williams puts his creative spin on these shoes, which have all the clean, classic details of the beloved Stan Smith.', 5, 1507598.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (93, 1, N'MEN''S ADIDAS RUNNING ZETA 1.0 SHOES', N'img/product/adidas/93.jpg', N'Designed to go the distance, these adidas Zeta 1.0 running shoes for men give optimum cushioning to your feet with full-length CLOUDFOAM and its stretch Mesh upper inspires comfortable familiarity. It''s smart style details balance the clean design and the rubber outsole provides best durability.', 5, 904438.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (94, 1, N'Men''s adidas Running PureBounce+ Clima Shoes', N'img/product/adidas/94.jpg', N'These running shoes are designed with 360 degrees of ventilation to help you stay cool on hot days. They have a lightweight and breathable mesh upper. A wide forefoot provides a stable platform for lateral movement, and energised cushioning provides comfort and flexibility.', 5, 1356808.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (95, 1, N'Men''s adidas Running Duramo 9 Shoes', N'img/product/adidas/95.jpg', N'These men''s versatile running shoes are ideal for the treadmill or the trail. They feature a mesh upper for breathability and a seamless print overlay for additional support. Pillow-soft Cloudfoam cushions every stride, while the durable outsole holds up to everyday wear.', 5, 994912.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (96, 1, N'MEN''S ADIDAS RUNNING HELKIN 3.0 SHOES', N'img/product/adidas/96.jpg', N'Style and performance go hand in hand in this adidas Helkin 3.0 Running shoes for men. The breathable upper Knit-Mesh offers maximum ventilation. EVA midsole and rubber outsole. ', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (97, 1, N'MEN''S ADIDAS RUNNING ARIUS 1.0 SHOES', N'img/product/adidas/97.jpg', N'The adidas Arius 1.0 Running shoes for men feature a comfortable two-tone Mesh upper with They come with Lightstrike IMEVA midsole for long term lightweight cushioning and shock absorption with a full rubber outsole for durability.', 5, 753648.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (98, 1, N'Men''s adidas Originals Skateboarding Seeley Shoes', N'img/product/adidas/98.jpg', N'Designed so they''re ready-to-ride with no wear-in time, these shoes draw on adidas heritage and reimagine it specifically for skateboarding. An abrasion-resistant suede upper holds up to daily park sessions, while the textile lining keeps your feet comfortable on or off the board. Tonal 3-Stripes and a linear Trefoil logo give these shoes low-key adidas style.', 5, 1085386.38, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (99, 1, N'MEN''S ADIDAS RUNNING HELKIN 3.0 SHOES', N'img/product/adidas/99.jpg', N'Style and performance go hand in hand in this adidas Helkin 3.0 Running shoes for men. The breathable upper Knit-Mesh offers maximum ventilation. EVA midsole and rubber outsole. ', 5, 693332.438, CAST(N'2021-10-19' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (100, 2, N'Nike Air Force 1 ''07 Essential', N'img/product/nike/1.jpg', N'Let your shoe game shimmer in the Nike Air Force 1 ''07 Essential. It takes the classic AF-1 design to the next level with its premium leather upper and iridescent Swoosh.', 10, 2260342, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (101, 2, N'Nike Air Force 1 ''07', N'img/product/nike/2.jpg', N'The legend lives on in the Nike Air Force 1 ''07, a modern take on the iconic AF1 that blends classic style with fresh colours and details.', 10, 2260342, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (102, 2, N'Nike Air Force 1 Sage Low LX', N'img/product/nike/3.jpg', N'Taking both height and craft to new levels, the Nike Air Force 1 Sage Low LX features a platform midsole and pared-down upper. Rolled edges and clean lines replace traditional overlays for a bold look.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (103, 2, N'Nike Air Max Dia SE', N'img/product/nike/4.jpg', N'Designed for a woman''s foot, the Nike Air Max Dia delivers a lifted look and airy aesthetic in a sleek shape. The minimal upper modernises the look while the exaggerated midsole amplifies the Max Air unit surrounded by clear TPU for a boost of style.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (104, 2, N'Nike Air Max Verona', N'img/product/nike/5.jpg', N'Pass on the good vibes in the Nike Air Max Verona. Elegant and versatile, its mixed-material upper features a plush collar, flashy colours and unique stitching patterns. The Nike Air cushioning adds a modern twist, comfort and style to your journey.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (105, 2, N'Nike Free Metcon 3', N'img/product/nike/6.jpg', N'The Nike Free Metcon 3 combines the flexibility of a Nike Free sole with the flat, wide heel of the Metcon to keep you fast but stable on your feet from weightlifting to speed drills.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (106, 2, N'NikeCourt Blanc', N'img/product/nike/7.jpg', N'Inspired by heritage models, the NikeCourt Blanc goes with anything and everything. Leather in the upper gives you a clean look with pops of colour for a simple, versatile style that nods to the past.', 10, 1807972.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (107, 2, N'Nike Zoom Pegasus Turbo 2', N'img/product/nike/8.jpg', N'The Nike Zoom Pegasus Turbo 2 is updated with a feather-light upper, while innovative foam brings revolutionary responsiveness to your long-distance training.', 10, 4823772, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (108, 2, N'Nike Air Max 270 React ENG', N'img/product/nike/9.jpg', N'The Nike Air Max 270 React ENG combines a full-length React foam midsole with a 270 Max Air unit for unrivalled comfort and a striking visual experience.', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (109, 2, N'Nike Air Max 90', N'img/product/nike/10.jpg', N'Clean lines, versatile and timelessâ€”the people''s shoe returns with the Nike Air Max 90. Featuring the same iconic Waffle sole, stitched overlays and classic TPU accents you''ve come to love, it lets you walk among the pantheon of Air.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (110, 2, N'Nike Air Force 1 ''07', N'img/product/nike/11.jpg', N'The radiance lives on in the Nike Air Force 1 ''07, the b-ball OG that puts a fresh spin on what you know best: crisp leather in an all-white colourway for a statement look on and off the court.', 10, 2260342, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (111, 2, N'Jordan Air Max 200 XX', N'img/product/nike/12.jpg', N'With design inspiration taken from the iconic AJ8, the Jordan Air Max 200 XX features enhanced cushioning for all-day, street-ready comfort.', 10, 3165082, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (112, 2, N'Nike SuperRep Go', N'img/product/nike/13.jpg', N'The Nike SuperRep Go combines comfortable foam cushioning, flexibility and support to get you moving in circuit-based fitness classes or while streaming workouts at home.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (113, 2, N'Nike Air VaporMax Flyknit 3', N'img/product/nike/14.jpg', N'Be bouncy and buoyant in the Nike Air VaporMax Flyknit 3. Inspired by high fashion, the upper features flowing lines of breathable, stretchable Flyknit construction. Revolutionary VaporMax Air technology keeps a spring in your step with toe-to-heel cushio', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (114, 2, N'Nike Air Zoom SuperRep', N'img/product/nike/15.jpg', N'The Nike Air Zoom SuperRep is designed for circuit training, HIIT, short runs and other fast-paced exercise. Zoom Air cushioning in the forefoot combines with a wide, stable heel to keep you moving and lifting comfortably.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (115, 2, N'Nike Air Max 270 React ENG', N'img/product/nike/16.jpg', N'Refresh your step in the Nike Air Max 270 React ENG. Featuring all the forward-looking design and innovation of the OG Air Max 270, it offers sleek lines and radiating TPU fingers that dole out the fresh style. Lightweight, no-sew materials create a time-', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (116, 2, N'Nike Air Max 97', N'img/product/nike/17.jpg', N'The Nike Air Max 97 keeps a sneaker icon going strong with the same design details that made it famous: water-ripple lines, reflective piping and full-length Max Air cushioning.', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (117, 2, N'Nike Air Force 1 ''07', N'img/product/nike/18.jpg', N'The legend lives on in the Nike Air Force 1 ''07â€”a modern take on the iconic AF1 that blends classic style with sweet details. A stitched tag logo runs down the tongue while over-branding throughout reinforces Nike heritage.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (118, 2, N'Nike Court Vintage Premium', N'img/product/nike/19.jpg', N'The Nike Court Vintage Premium embodies ''80s tennis at its bestâ€”laid-back and stylish. The smooth leather upper is combined with micro-branding for a relaxed look and feel, while the cushioned sockliner provides smooth comfort with every step.', 10, 1657182.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (119, 2, N'Nike Air Max 97', N'img/product/nike/20.jpg', N'Remastered from the OG that shook up the running world, the Nike Air Max 97 elevates the classic design. Bold new colours draw inspiration from the Hanshin Tigers, one of Japan''s oldest baseball teams.', 10, 4823772, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (120, 2, N'Air Jordan XXXIV PF', N'img/product/nike/21.jpg', N'The Air Jordan XXXIV PF continues the legacy of a cultural icon. Light, responsive and sculpted with aerodynamic precision, it combines a boldly unconventional midsole with herringbone traction to merge innovative and iconic design elements.', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (121, 2, N'Nike Metcon 5', N'img/product/nike/22.jpg', N'The Nike Metcon 5 is the most tuned Metcon yet. This means specific stability for heavy lifting, traction made for speed and durability where you need it. It even includes a Hyperlift insert that''s compatible with all prior versions of the Metcon. Meet yo', 10, 3315872, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (122, 2, N'Nike React Phantom Run Flyknit 2', N'img/product/nike/23.jpg', N'The Nike React Phantom Run Flyknit 2 offers versatility for the everyday runner. Building on the foundation of its predecessor, the shoe expands on its laceless design by adding secure support that feels like it "disappears" on your foot. More foam means ', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (123, 2, N'Nike Joyride Run Flyknit', N'img/product/nike/24.jpg', N'The Nike Joyride Run Flyknit is designed to help make running feel easier and give your legs a day off. Tiny foam beads underfoot contour to your foot for cushioning that stands up to your mileage.', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (124, 2, N'Nike Air Max 90', N'img/product/nike/25.jpg', N'With colours fresher than summer flowers, this take on the ''90s champion brings you the comfort and look you trustâ€”visible Max Air cushioning, bold TPU accents and plush padding around the ankle.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (125, 2, N'Nike Air VaporMax 360', N'img/product/nike/26.jpg', N'Inspired by heritage running shoes like the 2006 Air Max 360, the Nike Air VaporMax 360 re-imagines full-length Air with its lighter, more flexible design. The full-length foam midsole adds to the comfort while bold colours create a fresh, modern look.', 10, 5728512, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (126, 2, N'Nike Offcourt', N'img/product/nike/27.jpg', N'Featuring Revive Foam, a super-soft foam designed to help you relax and recharge, the unrelenting comfort of the Nike Offcourt Slide is sensational. The innovative dual-layered foam and soft jersey lining on the strap ensure a gratifying full-foot experie', 10, 752442.1, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (127, 2, N'Nike React Phantom Run Flyknit 2', N'img/product/nike/28.jpg', N'The Nike React Phantom Run Flyknit 2 is all about versatility for the everyday runner. The shoe expands on its laceless design by adding secure comfort, making it feel like the shoe disappears on your foot. More foam means better cushioning, keeping you c', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (128, 2, N'LeBron 7 QS', N'img/product/nike/29.jpg', N'Make your head-turning journey to the top comfortable. Built strong and sleek, the LeBron 7 QS features a mix of materials on the upper for a look that lasts. Metal accents and multiple LeBron crests celebrate a king, while full-length cushioning graces y', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (129, 2, N'Nike In-Season TR 9', N'img/product/nike/30.jpg', N'The Nike In-Season TR 9 is light, stable and features deep, comfortable footbed for superior impact absorption and energy return throughout your entire workout.', 10, 1807972.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (130, 2, N'Nike Joyride Run FlyKnit', N'img/product/nike/31.jpg', N'The Nike Joyride Run Flyknit is designed to help make running feel easier and give your legs a day off. Tiny foam beads underfoot contour to your foot for cushioning that stands up to your mileage.', 10, 3618055.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (131, 2, N'Nike ZoomX Vista Grind', N'img/product/nike/32.jpg', N'Edgy and funâ€”the Nike ZoomX Vista Grind is proof of the improbable, bringing you to a bold new place that''s rebellious and forward thinking. Using recycled foam from the Nike ZoomX family, it takes Nike DNA and combines it with lightweight mesh, exagger', 10, 4220612, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (132, 2, N'Nike Air Force 1 Sage Low', N'img/product/nike/33.jpg', N'Taking old-school b-ball style to new levels, the Nike Air Force 1 Sage Low features a platform midsole and a pared-down upper for a boldly feminine look. Colour accents around the Swoosh and on the heel and tongue add a fresh take to any summertime outfi', 10, 2712712, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (133, 2, N'Nike Air Max 720', N'img/product/nike/34.jpg', N'The Nike Air Max 720 goes bigger than ever before with Nike''s tallest Air unit yet, which offers more air underfoot for unprecedented, all-day comfort. Has Air Max gone too far? We hope so.', 10, 4823772, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (134, 2, N'Air Jordan 1 Mid SE', N'img/product/nike/35.jpg', N'The Air Jordan 1 Mid SE maintains the timeless appeal of the OG AJ1, revamped with fresh colours and premium materials. Built with a lightweight Air-Sole unit and classic design lines, it captures the essence of the original through a modern lens.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (135, 2, N'Nike Daybreak', N'img/product/nike/36.jpg', N'Originally released in 1979, the Nike Daybreak is a blast from the past. Featuring the same rubber Waffle outsole and nylon upper, it gives you true vintage style.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (136, 2, N'Nike SB Shane', N'img/product/nike/37.jpg', N'Shane O''Neill put the same attention to detail into every aspect of his signature shoe as he does in his almost otherworldly skating. From the low-key perforated ventilation at the toe, to the double lacing option and the no-break-in remastered sole, the ', 10, 1958762.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (137, 2, N'Air Jordan 1 Mid', N'img/product/nike/38.jpg', N'The Air Jordan 1 Mid Shoe is inspired by the first AJ1, offering OG fans a look at how far the Jordan brand has come since 1985.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (138, 2, N'Nike Air Max 270 React', N'img/product/nike/39.jpg', N'Refresh your step in the Nike Air Max 270 React. It uses lightweight, no-sew materials to create a modern aesthetic that looks as good as it feels.', 10, 3919032, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (139, 2, N'Nike Air Max 98', N'img/product/nike/40.jpg', N'Always one step ahead, the Nike Air Max 98 features the OG design lines that were inspired by the walls of the Grand Canyon, while adding bursts of fresh colour to the upper. The fluid, textured look and full-length Nike Air cushioning set you apart from ', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (140, 2, N'Nike Joyride Dual Run Premium', N'img/product/nike/41.jpg', N'The Nike Joyride Dual Run Premium blazes its own route. Tiny foam beads underfoot are combined with cushioning in the forefoot for an incredibly smooth feel that contours to your foot. Colourful skins throughout the upper give it a deluxe look.', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (141, 2, N'Nike Free RN Flyknit 3.0 2020', N'img/product/nike/42.jpg', N'The Nike Free RN Flyknit 3.0 2020 is a huge leap forward in the evolution of the Free. Its stretchy design is mixed with a supportive upper for a secure sensation that moves with your foot. Lighter and closer to the ground than previous versions, it gives', 10, 3315872, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (142, 2, N'Nike Mercurial Vapor 13 Elite Neymar Jr. FG', N'img/product/nike/43.jpg', N'Building on the 360 innovation of the 12, the Nike Mercurial Vapor 13 Elite Neymar Jr. FG adds a Nike Aerowtrac zone to the forefoot and a slightly stiffer chassis to help supercharge traction. Inside, an insole with NikeGrip technology provides maximum i', 10, 6934832, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (143, 2, N'PG 4 EP', N'img/product/nike/44.jpg', N'Paul George is the rare high-percentage shooter who''s also a coach''s dream on D. Designed for his unrivalled 2-way game, the PG 4 EP unveils a new cushioning system that''s lightweight, articulated and responsive: ideal for players like Paul who go hard ev', 10, 2712712, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (144, 2, N'Air Max 97 LX', N'img/product/nike/45.jpg', N'Inspired by a high-speed bullet train, the Nike Air Max 97 LX brings back a running icon with a plush, lightweight upgrade. It modernises a retro design with a moulded upper, welded overlays and a Max Air unit for all-day comfort.', 10, 4823772, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (145, 2, N'Nike Air Max 90', N'img/product/nike/46.jpg', N'Redesigned for casual wear, the Nike Air Max 90 stays true to its ''90s running roots. Bold colours add a fresh look while Max Air cushioning adds all-day comfort. Iconic details like the rubber Waffle sole, stitched overlays and TPU plates nod to your her', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (146, 2, N'Jordan ''Why Not?'' Zer0.3 PF', N'img/product/nike/47.jpg', N'One of the game''s fiercest competitors, triple-double dynamo Russell Westbrook has the motor, muscle and mentality to match his fearlessnessâ€”with the stats to back it up. Built to hold up on outdoor courts, the Jordan "Why Not?" Zer0.3 PF is fine-tuned ', 10, 3315872, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (147, 2, N'Nike Air Zoom SuperRep', N'img/product/nike/48.jpg', N'The Nike Air Zoom SuperRep is designed for circuit training, HIIT, short runs and other fast-paced exercise. Zoom Air cushioning in the forefoot combines with a wide, stable heel to keep you moving and lifting comfortably.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (148, 2, N'Nike Metcon 5 AMP', N'img/product/nike/49.jpg', N'The Nike Metcon 5 AMP arms you with stability for heavy lifting and traction for sprints during high-impact training. It combines breathability and durability to be your secret weapon in the gym.', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (149, 2, N'Nike Air Max Tailwind 99', N'img/product/nike/50.jpg', N'The Nike Air Max Tailwind 99 has a storied history, beginning in 1979 with the original Nike Air project. To celebrate 20 years of the Tailwind, this model blends elements from several decades past. An OG colourway nods to the shoe''s initial debut back in', 10, 3376791.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (150, 2, N'Nike Mercurial Vapor 13 Club IC', N'img/product/nike/51.jpg', N'The Nike Mercurial Vapor 13 Club IC is made for high-speed play. A synthetic upper wraps your foot for streamlined speed, while a rubber outsole gives you the traction you need to strike fast.', 10, 1506392.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (151, 2, N'Nike Air Max 97', N'img/product/nike/52.jpg', N'The Air Max 97 shook up the running world with its revolutionary full-length Nike Air unit. The Nike Air Max 97 remasters the original design with bold new colours and flashes of gold.', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (152, 2, N'Nike Air Max Triax', N'img/product/nike/53.jpg', N'Keep your fire burning in the Nike Air Max Triax. It features the same iconic shape and large-volume Air unit as the OG, bringing back the classic comfort and style that''s known and loved.', 10, 3315872, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (153, 2, N'LeBron 17 Low', N'img/product/nike/54.jpg', N'Fine-tuned with LeBron''s ferocious game in mind, the LeBron 17 Low has a sleek, low-top design that features a powerful combination of impact-ready cushioning and responsiveness.', 10, 4220612, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (154, 2, N'Nike Air Max 2090', N'img/product/nike/55.jpg', N'Bring the past into the future with the Nike Air Max 2090. Inspired by the iconic Air Max 90, the 2090 features Nike Air cushioning underfoot that provides unparalleled comfort, while transparent mesh on the upper is blended with timeless OG features for ', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (155, 2, N'Nike Renew Fusion', N'img/product/nike/56.jpg', N'The Nike Renew Fusion blends stability, cushioning and durability for high-impact training sessions. A foam sole cushions heavy-weight, high-paced activities, while a midfoot cage locks your foot down to a flat, wide base for stability.', 10, 2109552, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (156, 2, N'LeBron 17', N'img/product/nike/57.jpg', N'The LeBron 17 harnesses LeBron''s strength and speed with containment and support for all-court domination. It features a lightweight mix of knit and heat-moulded yarns that gives each one a durable look and feel. Combined cushioning provides LeBron with t', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (157, 2, N'Nike Air Max 720 OBJ Slip', N'img/product/nike/58.jpg', N'Taking its design inspiration from top wide receiver and fashion icon Odell Beckham Jr., the Nike Air Max 720 OBJ Slip brings some serious heat to your feet. Layered materials like suede, mesh and webbing combine for an eye-catching, tech-driven look.', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (158, 2, N'Nike SuperRep Go', N'img/product/nike/59.jpg', N'The Nike SuperRep Go combines comfortable foam cushioning, flexibility and support to get you moving in circuit-based fitness classes or while streaming workouts at home.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (159, 2, N'Nike Air Max 90 Premium', N'img/product/nike/60.jpg', N'The Nike Air Max 90 Premium is built in honour of celebrated Parisian bakers who define French cuisine and hard work. Nike Air cushioning under your feet feels softer than freshly baked brioche while a durable upper features a French flag and baking champ', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (160, 2, N'Nike Epic Phantom React A.I.R. Cody Hudson', N'img/product/nike/61.jpg', N'Soft to the touch, the Nike Epic Phantom React A.I.R. lets go of laces for slip-on style that has you up and running in no time. A sock-like fit within breathable Flyknit feels as though the Phantom "disappears" as you run, while a polka-dotted upper gets', 10, 2532367.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (161, 2, N'Nike Air Max 90', N'img/product/nike/62.jpg', N'Clean lines, versatile and timelessâ€”the people''s shoe returns with the Nike Air Max 90. Featuring the same iconic Waffle sole, stitched overlays and classic TPU accents you''ve come to love, it lets you walk among the pantheon of Air.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (162, 2, N'Nike Mercurial Superfly 7 Club TF', N'img/product/nike/63.jpg', N'The Nike Mercurial Superfly 7 Club TF features a low-profile Dynamic Fit collar and synthetic material in the upper that wraps your foot for streamlined speed.', 10, 1807972.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (163, 2, N'Nike Zoom Gravity', N'img/product/nike/64.jpg', N'Designed to make fast go faster, the Nike Zoom Gravity is built to take you from quick tempo runs to winning races. Snappy forefoot propulsion and grippy, multi-surface traction combine to maximize your stride.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (164, 2, N'Nike Air Max 270 React ENG', N'img/product/nike/65.jpg', N'The Nike Air Max 270 React ENG combines a full-length React foam midsole with a 270 Max Air unit for unrivalled comfort and a striking visual experience.', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (165, 2, N'Nike Air Force 1 Type', N'img/product/nike/66.jpg', N'The Nike Air Force 1 Type brings a handmade aesthetic to a classic look. Using transparent materials to show off a closure system and adjustable technology, it offers a unique look, custom fit and versatile styling options.', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (166, 2, N'Nike Air Max 270 React', N'img/product/nike/67.jpg', N'The bold silhouette of Nike Air lifts the Nike Air Max 270 React to new heights, while the Nike React foam midsole delivers exceptional cushioning. Imagine all-day comfort with unstoppable style.', 10, 2351419.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (167, 2, N'Nike React Presto', N'img/product/nike/68.jpg', N'Inspired by the early 2000s original, the Nike React Presto puts an exaggerated spin on an unconventional icon. Nike React foam delivers an expressive look with a lightweight, bouncy feel and a whole lot of personality.', 10, 1808575.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (168, 2, N'Nike Legend React', N'img/product/nike/69.jpg', N'The Nike Legend React Men''s Running Shoe features a breathable upper with synthetic overlays that enhance durability while smooth, responsive foam cushions every step as you run.', 10, 2652396, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (169, 2, N'Air Jordan 1 Low SE', N'img/product/nike/70.jpg', N'Always fresh and never out of style, the Air Jordan 1 Low is one of the most iconic sneakers of all time. This SE version shakes up the classic design with flavourful new colour schemes and trim details.', 10, 2712712, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (170, 2, N'NikeCourt Air Max Wildcard', N'img/product/nike/71.jpg', N'The NikeCourt Air Max Wildcard delivers the comfort you need to hit hard and move fast on the court. A Max Air unit under your heel cushions every step, while an innovative Lunarlon midsole provides a springy underfoot sensation and extra stability.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (171, 2, N'Zoom LeBron 3 QS', N'img/product/nike/72.jpg', N'Originally released in 2006, the Zoom LeBron 3 QS brings royalty to the street in the third iteration of the King''s signature line. Nike Zoom Air cushioning, premium leather details and a throwback lion logo make this shoe a first draft pick.', 10, 4522192, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (172, 2, N'Nike Free Metcon 3', N'img/product/nike/73.jpg', N'The Nike Free Metcon 3 combines Nike Free flexibility around the forefoot with Metcon stability in the heel to help you get the most out of your training session.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (173, 2, N'KD Trey 5 VII EP', N'img/product/nike/74.jpg', N'Kevin Durant likes a shoe that feels broken-in straight away but still provides containment and support. The KD Trey 5 VII EP hits the ground running with a combination of bouncy cushioning with a precise, supportive fit that''s ready to go right out of th', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (174, 2, N'Nike Mercurial Vapor 13 Academy TF', N'img/product/nike/75.jpg', N'The soft upper of the Nike Mercurial Vapor 13 Academy TF Shoe wraps your foot for a second-skin fit, while the rubber outsole helps super-charge traction on turf.', 10, 2260342, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (175, 2, N'Jordan React Havoc SE', N'img/product/nike/76.jpg', N'An update to the ultra-fast Jordan React Havoc, the SE maintains its responsive cushioning combination while revamping elements of the upper. The transparent heel clip offers the same great heel lockdown but with a new aesthetic. A synthetic suede and str', 10, 3315872, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (176, 2, N'Nike SB Air Max Stefan Janoski 2', N'img/product/nike/77.jpg', N'The Nike SB Air Max Stefan Janoski 2 hugs your foot with a breathable textile upper. A Max Air unit in the heel cushions every step, while a flat rubber outsole optimises grip when you''re on your board.', 10, 3014292, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (177, 2, N'Nike Free RN Flyknit 3.0', N'img/product/nike/78.jpg', N'Ideal for runs up to 3 miles, the Nike Free RN Flyknit 3.0 delivers a lace-free design so you can slip in and hit your stride. An updated flex groove pattern and modified midsole foam provides more flexibility than its predecessor, creating a barefoot sen', 10, 2321261.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (178, 2, N'Nike Phantom Venom Academy FG', N'img/product/nike/79.jpg', N'The Nike Phantom Venom Academy FG is engineered for powerful, precise strikes that win games. Ridges on the instep create spin to control the flight of the ball, while the firm-ground plate provides the traction needed to unleash at any moment.', 10, 2260342, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (179, 2, N'Nike Air Ghost Racer', N'img/product/nike/80.jpg', N'Designed for speed, stability and comfort, the Nike Air Ghost Racer was a hit 20 years agoâ€”and now it''s back in a stitch-for-stitch remake. And though it has all the same features as the original, it might be even better than you remember.', 10, 2110155.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (180, 2, N'Nike ACG Air Terra Antarktik', N'img/product/nike/81.jpg', N'Designed and tested in Oregon, the Nike ACG Antarktik is a "jacket" for your foot. Its tough ripstop upper combines with a GORE-TEX lining to help keep your foot dry. All-new lug details use hard rubber for traction in all conditions.', 10, 4823772, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (181, 2, N'Nike Air Max 2 Light', N'img/product/nike/82.jpg', N'Originally released in 1994, the Nike Air Max 2 Light returns as a near-exact replica of the iconic runner. A mesh and synthetic leather upper, moulded heel and vibrant Air Max unit honour the OG. The soft foam midsole optimises all-day comfort.', 10, 2894263.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (182, 2, N'Nike Mercurial Superfly 7 Academy MG', N'img/product/nike/83.jpg', N'Building on the forefoot plate innovation of the 6, the Nike Mercurial Superfly 7 Academy MG Boot adds a versatile multi-ground plate that provides traction on natural- and artificial-grass surfaces.', 10, 2561922, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (183, 2, N'Nike AlphaDunk', N'img/product/nike/84.jpg', N'Join the hoops uprising in the AlphaDunk, one of Nike Basketball''s bounciest game shoes to date. The revamped upper construction is light and supportive and a large cushioning unit spans nearly the entire forefoot, giving you all the responsiveness you ca', 10, 3376791.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (184, 2, N'Nike Daybreak SP', N'img/product/nike/85.jpg', N'The Nike Daybreak SP marks the return of the 1979 original, featuring suede and nylon on the upper and old-school graphics on the tongue for a ''70s runner-inspired look and feel.', 10, 1446679.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (185, 2, N'Nike x MMW Joyride CC3 Setter', N'img/product/nike/86.jpg', N'Alyx founder and creative director Matthew M. Williams is known for his ability to push fashion into new spaces. His angle is simple: Combine the influence of his life in New York and California with the latest innovations. The Nike x MMW Joyride CC3 Sett', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (186, 2, N'Nike Air Max 95 SP', N'img/product/nike/87.jpg', N'Taking inspiration from the human body, the Nike Air Max 95 SP mixes unbelievable comfort with running DNA. The iconic side panels represent muscles, while Nike Air in the heel and forefoot cushions your every step.', 10, 3376791.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (187, 2, N'Nike SB Blazer Low GT', N'img/product/nike/88.jpg', N'The Nike SB Blazer Low GT pairs a supportive feel with lightweight, responsive cushioning for everyday use. Just like Grant Taylor, it blends contemporary style with old-school traditions.', 10, 2109552, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (188, 2, N'LeBron 17 Monstars', N'img/product/nike/89.jpg', N'The Monstars have crash-landed in the Windy City, prepared to strip us of some of our greatest hardwood heroes. With the game in danger, who can Bugs and the Tune Squad turn to? Who other than The King himself, LeBron James, poised to dash the hopes and d', 10, 5125352, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (189, 2, N'Nike Air Max Impact', N'img/product/nike/90.jpg', N'The Nike Air Max Impact infuses bold, expressive details into a design that''s a beast on the court. Responsive cushioning helps soften hard landings, while the moulded heel clip and dual-strap system combine for a lightweight, locked-in feel.', 10, 2411132, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (190, 2, N'Nike Air Max 90 QS', N'img/product/nike/91.jpg', N'Originally designed by Tinker Hatfield in 1990, the Air Max 90 has been re-imagined. Widely considered one of the biggest cross-cultural icons of the early ''00s, this iteration pays tribute to the influential 2003 "Snakeskin" release with premium material', 10, 3617452, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (191, 2, N'Nike React Element 55 SE', N'img/product/nike/92.jpg', N'The Nike React Element 55 SE borrows design lines from heritage runners like the Nike Internationalist, then places it all on Nike React technology.', 10, 1989523.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (192, 2, N'Jordan Proto-Max 720', N'img/product/nike/93.jpg', N'Inspired by outer space flight, the Jordan Proto-Max 720 provides all-day comfort with a future-forward look. An outer shroud covers the sock-like bootie construction, while Nike Air cushions every step.', 10, 3859319.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (193, 2, N'Nike Phantom Vision 2 Academy Dynamic Fit MG', N'img/product/nike/94.jpg', N'The Nike Phantom Vision 2 Academy Dynamic Fit MG brings a new level of fierce precision to the pitch. A foot-hugging inner sleeve is concealed in a NIKESKIN upper to create a boot for the finishers, the providers and the battlers of today''s game.', 10, 2561922, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (194, 2, N'Nike React Element 55 SE', N'img/product/nike/95.jpg', N'The Nike React Element 55 SE borrows design lines from heritage runners like the Nike Internationalist, adds reflective graphics, then places it all on Nike React technology.', 10, 1989523.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (195, 2, N'Nike Air Max2 Light', N'img/product/nike/96.jpg', N'Originally released in 1994, the Nike Air Max2 Light returns as a near-exact replica of the iconic runner with style for the street. Its mesh and synthetic upper, moulded heel and Max Air unit honour the OG, while the soft foam midsole optimises all-day c', 10, 2532367.25, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (196, 2, N'Nike Air Max 270', N'img/product/nike/97.jpg', N'Nike''s first lifestyle Air Max lets you greet the streets with the soft, smooth and resilient ride of the Nike Air Max 270. The design draws inspiration from the Air Max pantheon, showcasing Nike''s greatest innovation with its large window and fresh array', 10, 4220612, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (197, 2, N'Nike Phantom Vision 2 Club Dynamic Fit MG', N'img/product/nike/98.jpg', N'The Nike Phantom Vision 2 Club Dynamic Fit MG brings fierce precision to the pitch. A foot-hugging inner sleeve is concealed in textured leather for comfortable, precise touch.', 10, 1807972.13, CAST(N'2021-10-20' AS Date))
GO
INSERT [dbo].[Product] ([id], [idBrand], [name], [image], [describe], [quantity], [cost], [saleDate]) VALUES (198, 2, N'Nike Air Force 1 ''07 LV8', N'img/product/nike/99.jpg', N'The Nike Air Force 1 ''07 LV8 has the same hoops-inspired performance of the ''82 OG plus fresh new patterns for a sleek look that turns heads.', 10, 2290500, CAST(N'2021-10-20' AS Date))
GO
SET IDENTITY_INSERT [dbo].[Product] OFF
GO

-- Account (id, username, password, fullname, avatar, phoneNumber, address, sex, dateOfBirth, isAdmin)
insert into Account(username, password, fullname, avatar, phoneNumber, address, sex, dateOfBirth, isAdmin)
	values('nam', 'namnamnam', N'Thái Thành Nam', 'img/avatar/nam.jpg', '0981771024', N'Bến Tre', 'Male', '2001-11-28', 0);
insert into Account(username, password, fullname, avatar, phoneNumber, address, sex, dateOfBirth, isAdmin)
	values('tan', 'tantantan', N'Cao Hoài Tấn', 'img/avatar/tan.jpg', '0983234434', N'Bình Định', 'Male', '2001-09-02', 0);
insert into Account(username, password, fullname, avatar, phoneNumber, address, sex, dateOfBirth, isAdmin)
	values('trung', 'trungtrungtrung', N'Nguyễn Ngọc Trung', 'img/avatar/trung.jpg', '0934534534', N'Phú Yên', 'Male', '2001-02-14', 0);
insert into Account(username, password, fullname, avatar, phoneNumber, address, sex, dateOfBirth, isAdmin)
	values('toan', 'toantoantoan', N'Nguyễn Phúc Thanh Toàn', 'img/avatar/toan.jpg', '0986537469', N'Tây Ninh', 'Male', '2001-01-01', 0);
insert into Account(username, password, fullname, avatar, phoneNumber, address, sex, dateOfBirth, isAdmin)
	values('admin', 'adminadminadmin', 'Admin', 'img/avatar/admin.jpg', '0999999999', N'TP.HCM', 'Male', '2001-01-01', 1);

-- Comment (id, idProduct, username, comment)
insert into Comment(idProduct, username, comment) values(1, 'nam', N'Sản phẩm rất tuyệt vời!')
insert into Comment(idProduct, username, comment) values(21, 'nam', N'Sản phẩm rất tuyệt vời!')
insert into Comment(idProduct, username, comment) values(43, 'nam', N'Sản phẩm rất tuyệt vời!')
insert into Comment(idProduct, username, comment) values(45, 'nam', N'Sản phẩm rất tuyệt vời!')
insert into Comment(idProduct, username, comment) values(65, 'nam', N'Sản phẩm rất tuyệt vời!')

insert into Comment(idProduct, username, comment) values(27, 'tan', N'Sản phẩm rất đẹp!')
insert into Comment(idProduct, username, comment) values(2, 'tan', N'Sản phẩm rất đẹp!')
insert into Comment(idProduct, username, comment) values(4, 'tan', N'Sản phẩm rất đẹp!')
insert into Comment(idProduct, username, comment) values(32, 'tan', N'Sản phẩm rất đẹp!')
insert into Comment(idProduct, username, comment) values(10, 'tan', N'Sản phẩm rất đẹp!')

insert into Comment(idProduct, username, comment) values(3, 'trung', N'Sản phẩm rất xịn!')
insert into Comment(idProduct, username, comment) values(5, 'trung', N'Sản phẩm rất xịn!')
insert into Comment(idProduct, username, comment) values(43, 'trung', N'Sản phẩm rất xịn!')
insert into Comment(idProduct, username, comment) values(12, 'trung', N'Sản phẩm rất xịn!')
insert into Comment(idProduct, username, comment) values(23, 'trung', N'Sản phẩm rất xịn!')

insert into Comment(idProduct, username, comment) values(5, 'toan', N'Sản phẩm rất đáng giá!')
insert into Comment(idProduct, username, comment) values(6, 'toan', N'Sản phẩm rất đáng giá!')
insert into Comment(idProduct, username, comment) values(23, 'toan', N'Sản phẩm rất đáng giá!')
insert into Comment(idProduct, username, comment) values(63, 'toan', N'Sản phẩm rất đáng giá!')
insert into Comment(idProduct, username, comment) values(26, 'toan', N'Sản phẩm rất đáng giá!')

-- Cart (id, username, idProduct, quantity, cost)
insert into Cart(username, idProduct, quantity) values('nam', 2, 1)
insert into Cart(username, idProduct, quantity) values('nam', 12, 2)
insert into Cart(username, idProduct, quantity) values('nam', 21, 1)
insert into Cart(username, idProduct, quantity) values('nam', 4, 2)
insert into Cart(username, idProduct, quantity) values('nam', 23, 1)

insert into Cart(username, idProduct, quantity) values('tan', 56, 1)
insert into Cart(username, idProduct, quantity) values('tan', 1, 2)
insert into Cart(username, idProduct, quantity) values('tan', 12, 1)
insert into Cart(username, idProduct, quantity) values('tan', 13, 2)
insert into Cart(username, idProduct, quantity) values('tan', 23, 1)

insert into Cart(username, idProduct, quantity) values('trung', 5, 2)
insert into Cart(username, idProduct, quantity) values('trung', 12, 1)
insert into Cart(username, idProduct, quantity) values('trung', 34, 2)
insert into Cart(username, idProduct, quantity) values('trung', 14, 1)
insert into Cart(username, idProduct, quantity) values('trung', 41, 2)

insert into Cart(username, idProduct, quantity) values('toan', 2, 2)
insert into Cart(username, idProduct, quantity) values('toan', 52, 1)
insert into Cart(username, idProduct, quantity) values('toan', 32, 2)
insert into Cart(username, idProduct, quantity) values('toan', 21, 1)
insert into Cart(username, idProduct, quantity) values('toan', 12, 2)

-- Order (id, username, cost, purchaseDate, address, phoneNumber, fullname)
insert into [Order](username, address, phoneNumber, fullname)
	values('nam', N'Bến Tre', '091771024', 'Nam')
insert into [Order](username, address, phoneNumber, fullname)
	values('tan', N'Bình Định', '0982736451', N'Tấn')
insert into [Order](username, address, phoneNumber, fullname)
	values('trung', N'Phú Yên', '0982761273', 'Trung')
insert into [Order](username, address, phoneNumber, fullname)
	values('toan', N'Tây Ninh', '0928236321', N'Toàn')

-- OrderDetail (idOrder, idProduct, quantity)
insert into OrderDetail(idOrder, idProduct, quantity) values(1, 23, 2)
insert into OrderDetail(idOrder, idProduct, quantity) values(2, 12, 2)
insert into OrderDetail(idOrder, idProduct, quantity) values(3, 2, 2)
insert into OrderDetail(idOrder, idProduct, quantity) values(4, 3, 2)
